FROM apache/airflow:2.3.3

COPY requirements.txt /requirements.txt

RUN pip install --user --upgrade pip

RUN pip install -r /requirements.txt

RUN pip install apache-airflow-providers-amazon
RUN pip install apache-airflow-providers-smtp